import { arbitrum, avalanche, base, mainnet, mantle, moonbeam, plasma, polygon } from "viem/chains"
import { ChainEnum } from "../data/chains"
import { ChainRpcConfig, DEFAULT_CONFIG } from "./config"

export const RPC_OVERRIDE_CHAINS: Record<string, ChainRpcConfig> = {
    [ChainEnum.BASE]: {
        chain: base,
        rpcs: [
            "https://base-rpc.publicnode.com",
            "https://base.llamarpc.com",
            "https://base.public.blockpi.network/v1/rpc/public",
            "https://1rpc.io/base",
            "https://base-pokt.nodies.app",
            "https://base.meowrpc.com",
            "https://base-mainnet.public.blastapi.io",
            "https://developer-access-mainnet.base.org",
            "https://base.drpc.org",
            "https://base.api.onfinality.io/public",
            "https://base.rpc.subquery.network/public",
            "https://api.zan.top/base-mainnet",
            "https://endpoints.omniatech.io/v1/base/mainnet/public",
            "https://base.lava.build",
            "https://0xrpc.io/base",
            "https://base.therpc.io",
        ],
        ...DEFAULT_CONFIG,
        minRequiredRpcs: 3,
    },
    [ChainEnum.POLYGON_MAINNET]: {
        chain: polygon,
        rpcs: [
            "https://polygon-bor-rpc.publicnode.com",
            "https://polygon-mainnet.public.blastapi.io",
            "https://polygon.lava.build",
            "https://polygon.drpc.org",
            "https://gateway.tenderly.co/public/polygon",
            "https://endpoints.omniatech.io/v1/matic/mainnet/public",
            "https://polygon.therpc.io",
            "https://rpc-mainnet.matic.quiknode.pro",
            "https://polygon-pokt.nodies.app",
            "https://polygon.gateway.tenderly.co",
            "https://polygon-rpc.com",
            "https://polygon.api.onfinality.io/public",
            "https://api.zan.top/polygon-mainnet",
            "https://polygon.rpc.subquery.network/public",
        ],

        ...DEFAULT_CONFIG,
        minRequiredRpcs: 3,
    },
    [ChainEnum.MANTLE]: {
        chain: mantle,
        rpcs: [
            "https://rpc.mantle.xyz",
            "https://1rpc.io/mantle",
            "https://api.zan.top/mantle-mainnet",
            "https://mantle-public.nodies.app",
            "https://mantle.drpc.org",
        ],
        ...DEFAULT_CONFIG,
    },
    [ChainEnum.ETHEREUM_MAINNET]: {
        chain: mainnet,
        rpcs: [
            "https://eth.llamarpc.com",
            "https://api.zan.top/eth-mainnet",
            "https://rpc.flashbots.net/fast",
            "https://rpc.owlracle.info/eth/70d38ce1826c4a60bb2a8e05a6c8b20f",
            "https://eth.merkle.io",
            "https://eth-mainnet.nodereal.io/v1/1659dfb40aa24bbb8153a677b98064d7",
            "https://rpc.payload.de",
            "https://ethereum-rpc.publicnode.com",
            "https://eth-mainnet.g.alchemy.com/v2/demo",
            "https://go.getblock.io/aefd01aa907c4805ba3c00a9e5b48c6b",
            "https://rpc.flashbots.net",
            "https://public-eth.nownodes.io",
            "https://ethereum-json-rpc.stakely.io",
            "https://eth.blockrazor.xyz",
            "https://eth.drpc.org",
            "https://ethereum.public.blockpi.network/v1/rpc/public",
            "https://ethereum-public.nodies.app",
            "https://0xrpc.io/eth",
        ],
        ...DEFAULT_CONFIG,
    },
    [ChainEnum.PLASMA_MAINNET]: {
        chain: plasma,
        rpcs: ["https://rpc.plasma.to", "https://plasma.drpc.org"],
        ...DEFAULT_CONFIG,
    },
    [ChainEnum.ARBITRUM_ONE]: {
        chain: arbitrum,
        rpcs: [
            "https://1rpc.io/arb",
            "https://api.zan.top/arb-one",
            "https://arbitrum.drpc.org",
            "https://arb1.lava.build",
            "https://public-arb-mainnet.fastnode.io",
            "https://arbitrum.gateway.tenderly.co",
            "https://arbitrum-one-rpc.publicnode.com",
        ],
        ...DEFAULT_CONFIG,
    },
    [ChainEnum.AVALANCHE_C_CHAIN]: {
        chain: avalanche,
        rpcs: [
            "https://avalanche-mainnet.gateway.tenderly.co",
            "wss://avalanche-c-chain-rpc.publicnode.com",
            "https://rpc.poolz.finance/avalanche",
            "https://1rpc.io/avax/c",
            "https://0xrpc.io/avax",
            "https://avalanche.drpc.org",
        ],
        ...DEFAULT_CONFIG,
    },
    [ChainEnum.MOONBEAM]: {
        chain: moonbeam,
        rpcs: [
            "https://moonbeam.unitedbloc.com",
            "https://1rpc.io/glmr",
            "https://moonbeam-rpc.dwellir.com",
            "https://moonbeam.public.blastapi.io",
            "https://moonbeam-rpc.publicnode.com",
            "https://moonbeam.drpc.org",
            "https://endpoints.omniatech.io/v1/moonbeam/mainnet/public",
            "https://rpc.api.moonbeam.network",
            "https://rpc.poolz.finance/moonbeam",
            "https://moonbeam.rpc.grove.city/v1/01fdb492",
            "https://moonbeam.api.onfinality.io/public",
        ],
        ...DEFAULT_CONFIG,
    },
}
